version: '3.9'

services:
  app-database: # Host name/address
    image: postgres
    restart: always
    ports:
      - 6500:5432 # Port
    environment:
      POSTGRES_USER: postgres # Username
      POSTGRES_PASSWORD: postgres # Password
      POSTGRES_DB: mydb # Database name

  app-database-admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
